# Generated by Django 4.0.4 on 2022-07-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_botuser_first_name_remove_botuser_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='rem_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
