# Generated by Django 4.0.4 on 2022-07-20 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_botuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referals', to='backend.botuser'),
        ),
    ]
