# Generated by Django 4.0.4 on 2022-07-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_botuser_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
