# Generated by Django 4.0.4 on 2022-07-20 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_botuser_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='bonus_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
