# Generated by Django 4.0.4 on 2022-07-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_botuser_bonus_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='cashback_bonus_percentage',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='botuser',
            name='referals_bonus_percentage',
            field=models.IntegerField(default=2),
        ),
    ]
