# Generated by Django 4.0.6 on 2022-07-30 10:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_botuser_username_botuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.TextField()),
                ('status_group', models.IntegerField(choices=[(0, '0 - Пользовательские'), (1, '1 - Новый'), (2, '2 - На исполнении'), (3, '3 - Отложенные'), (4, '4 - Исполненные'), (5, '5 - Доставка'), (6, '6 - Закрытые успешно'), (7, '7 - Закрытые неуспешно')])),
                ('text', ckeditor.fields.RichTextField()),
                ('created_at_duration', models.DurationField()),
                ('closed_at_duration', models.DurationField()),
                ('period', models.IntegerField()),
                ('repeat', models.IntegerField()),
                ('user_unique', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
    ]
