# Generated by Django 4.0.6 on 2022-07-30 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_ordermailing_alter_template_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermailing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermailing',
            name='orders',
            field=models.TextField(blank=True, default=''),
        ),
    ]
