# Generated by Django 4.0.6 on 2022-07-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_ordermailing_created_alter_ordermailing_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermailing',
            options={'verbose_name': 'Рассылка для заказа', 'verbose_name_plural': 'Рассылка для заказов'},
        ),
        migrations.AddField(
            model_name='ordermailing',
            name='users',
            field=models.ManyToManyField(to='backend.botuser'),
        ),
        migrations.AlterField(
            model_name='ordermailing',
            name='repeat',
            field=models.IntegerField(default=-1),
        ),
    ]
