# Generated by Django 4.0.6 on 2022-08-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_ordermailing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermailing',
            name='closed_at_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermailing',
            name='created_at_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
