# Generated by Django 4.0.6 on 2022-08-15 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_ordermailing_closed_at_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermailing',
            name='users',
        ),
        migrations.CreateModel(
            name='OrderMailingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ordermailing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.botuser')),
            ],
        ),
    ]
