# Generated by Django 4.0.6 on 2022-08-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_ordermailinguser_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermailing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='backend/images'),
        ),
    ]
