# Generated by Django 4.0.6 on 2022-08-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_ordermailing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMailingFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=255)),
                ('pattern', models.CharField(max_length=255)),
                ('order_mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='backend.ordermailing')),
            ],
        ),
    ]
